### ISSUE TITLE
add italian website datininja

### ISSUE THREAD

**Issue by EmidioStani** [NuCivic/dkan-sites#3]
http://dati.dataninja.it/

**Comment by acouch** [comment]
:+1:

**Comment by lukefretwell** [comment]
@EmidioStani is this still live? I'm getting an error on that page.

Additional uncaught exception thrown while handling exception.

Original

PDOException: SQLSTATE[28000] [1045] Access denied for user &#039;dataninja&#039;@&#039;localhost&#039; (using password: YES) in variable_initialize() (line 920 of /var/apps/dkan_dataninja/releases/20140518190849/includes/bootstrap.inc).

Additional

PDOException: SQLSTATE[28000] [1045] Access denied for user &#039;dataninja&#039;@&#039;localhost&#039; (using password: YES) in db_merge() (line 2445 of /var/apps/dkan_dataninja/releases/20140518190849/includes/database/database.inc).

**Comment by EmidioStani** [comment]
When I checked it was working
